{{- if .Values.secretStores }}
{{- range .Values.secretStores }}
{{- if or (eq .kind "SecretStore") (eq .kind "ClusterSecretStore") }}
apiVersion: external-secrets.io/v1beta1
kind: {{ .kind }}
metadata:
  name: {{ .name }}
  {{- if .namespace }}
  namespace: {{ .namespace }}
  {{- end }}
  labels:
    {{- include "spring-boot.labels" . | nindent 4 }}
    {{- if .labels }}
    {{- toYaml .labels | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "spring-boot.annotations" . | nindent 4 }}
    {{- if .annotations }}
    {{- toYaml .annotations | nindent 4 }}
    {{- end }}
spec:
  provider:
    {{- toYaml .provider | nindent 4 }}
  {{- if and .conditions (eq .kind "ClusterSecretStore") }}
  conditions:
    {{- toYaml .conditions | nindent 4 }}
  {{- end }}
  {{- if .controller }}
  controller: {{ .controller }}
  {{- end }}
  {{- if and .retrySettings (eq .kind "SecretStore") }}
  retrySettings:
    {{- toYaml .retrySettings | nindent 4 }}
  {{- end }}
---
{{- end }}
{{- end }}
{{- end }}

{{- if .Values.externalSecrets }}
{{- range .Values.externalSecrets }}
{{- if or (eq .kind "ExternalSecret") (eq .kind "ClusterExternalSecret") }}
apiVersion: external-secrets.io/v1beta1
kind: {{ .kind }}
metadata:
  name: {{ .name }}
  {{- if .namespace }}
  namespace: {{ .namespace }}
  {{- end }}
  labels:
    {{- include "spring-boot.labels" . | nindent 4 }}
    {{- if .labels }}
    {{- toYaml .labels | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "spring-boot.annotations" . | nindent 4 }}
    {{- if .annotations }}
    {{- toYaml .annotations | nindent 4 }}
    {{- end }}
spec:
  {{- toYaml .spec | nindent 2 }}
---
{{- end }}
{{- end }}
{{- end }}

{{- if .Values.pushSecrets }}
{{- range .Values.pushSecrets }}
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: {{ .name }}
  {{- if .namespace }}
  namespace: {{ .namespace }}
  {{- end }}
  labels:
    {{- include "spring-boot.labels" . | nindent 4 }}
    {{- if .labels }}
    {{- toYaml .labels | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "spring-boot.annotations" . | nindent 4 }}
    {{- if .annotations }}
    {{- toYaml .annotations | nindent 4 }}
    {{- end }}
spec:
  {{- toYaml .spec | nindent 2 }}
---
{{- end }}
{{- end }}

{{- if .Values.secretGenerators }}
{{- range .Values.secretGenerators }}
apiVersion: generators.external-secrets.io/v1alpha1
kind: {{ .kind }}
spec:
  {{- toYaml .spec | nindent 2 }}
---
{{- end }}
{{- end }}