# Default values for spring-boot.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

git:
  branch: master  
  # for projects based on maven modules, specify the top-level url in order to import the dependencies
  url: ""
  # for projects based on maven modules, builds the specified sub-module 
  module: ""
  
# specify a container image if you don't want to build from source 
container:
  image: "placeholder"
  registry: ""

# repository that contains the app manifest  
config:
  repo: ""
  # todo: add file path option

maven:
  mirror: ""

# base image for spring boot containers  
dockerfile:
  repo: https://github.com/prft-rh/dockerfile-java11.git

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  name:

podAnnotations: {}

# default Spring Boot port, override to reflect server.port config
service:
  port: 8080
  
management:
  port: 8081
  
env: {}
  #- name:
  #  value:
  #- name:
  #  value:
  # ...
  
resources:
  limits:
    cpu: 1
    memory: 600Mi
  requests:
    cpu: 500m
    memory: 400Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetRps: 400
  
version:
  name: ""
  branch: ""
  image: "placeholder"

# https://external-secrets.io/v0.7.2/api/secretstore/
# https://external-secrets.io/v0.7.2/api/clustersecretstore/
# https://external-secrets.io/v0.7.2/provider/aws-secrets-manager/

#externalSecretStores:
#  - name: # required; metadata
#    namespace: # optional; metadata
#    labels: # optional; metadata
#    annotations: # optional; metadata
#    kind: # required; SecretStore or ClusterSecretStore
#    provider: # required; the full yaml for a provider. examples: aws, azurekv, gcpsm, vault
#    conditions: # optional; only for ClusterSecretStore
#    controller: # optional
#    retrySettings: # optional; only for SecretStore

# https://external-secrets.io/v0.7.2/api/externalsecret/
# https://external-secrets.io/v0.7.2/api/clusterexternalsecret/

#externalSecretValues:
#  - name: # required; metadata
#    namespace: # optional; metadata
#    labels: # optional; metadata
#    annotations: # optional; metadata
#    kind: # required; ExternalSecret or ClusterExternalSecret
#    spec: # required; the full yaml for a external secret spec