name: DevOpsInABox

on:
  workflow_dispatch:
    inputs:
      increment_devops_version:
        type: choice
        description: Version increment for devopsinabox
        required: true
        default: 'patch'
        options:
        - major
        - minor
        - patch
      increment_catalog_version:
        type: choice
        description: Version increment for catalog
        required: true
        default: 'patch'
        options:
        - major
        - minor
        - patch
      first_run:
        type: choice
        description: Set to true only if first run
        required: true
        default: 'false'
        options:
        - true
        - false

jobs:
  build_devopsinabox:

    name: Build and Deploy DevOpsInABox
    runs-on: ubuntu-latest
    timeout-minutes: 4
    steps:

      - name: Set inputs
        run: |
          if ! [ ${GITHUB_REF#refs/heads/} == "aws" ] || [ ${GITHUB_REF#refs/heads/} == "azure" ]; then
            echo "::error::Branch must be 'aws' or 'azure'"
            exit 1
          else
            echo "BRANCH=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
          fi

          if [ -z "${{ inputs.increment_devops_version }}" ]; then
            echo "INCREMENT_DEVOPS_VERSION=patch" >> $GITHUB_ENV
          else
            echo "INCREMENT_DEVOPS_VERSION=$(echo ${{ inputs.increment_devops_version }})" >> $GITHUB_ENV
          fi

          if [ -z "${{ inputs.increment_catalog_version }}" ]; then
            echo "INCREMENT_CATALOG_VERSION=patch" >> $GITHUB_ENV
          else
            echo "INCREMENT_CATALOG_VERSION=$(echo ${{ inputs.increment_catalog_version }})" >> $GITHUB_ENV
          fi

          if [ -z "${{ inputs.first_run }}" ]; then
            echo "FIRST_RUN=false" >> $GITHUB_ENV
          else
            echo "FIRST_RUN=$(echo ${{ inputs.first_run }})" >> $GITHUB_ENV
          fi

          echo "ORGANIZATION=shawn_stout_org" >> $GITHUB_ENV
        shell: bash

      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Set versions
        run: |
          TAG_DATA=$(curl --location --request GET 'https://quay.io/api/v1/repository/'"$ORGANIZATION"'/devopsinabox-operator/tag?limit=100&onlyActiveTags=true' --header 'Authorization: Bearer $TOKEN')
          TAG_ARRAY=$(echo $TAG_DATA | jq .tags)
          if [ ${#TAG_ARRAY[@]} -eq 0 ]
          then
            TAG_VERSION="v0.0.0-$BRANCH"
            echo "OLD_VERSION=$(echo $TAG_VERSION)" >> $GITHUB_ENV
          else
            echo "$TAG_ARRAY" | jq -r '.[].name' | while read -r TAG_NAME; do
              if [[ $TAG_NAME == *-$BRANCH ]]
              then
                echo "OLD_VERSION=$(echo $TAG_NAME)" >> $GITHUB_ENV
                break
              fi
            done
          fi
          
          TAG_DATA=$(curl --location --request GET 'https://quay.io/api/v1/repository/'"$ORGANIZATION"'/operators-catalog/tag?limit=1&onlyActiveTags=true' --header 'Authorization: Bearer $TOKEN')
          TAG_VERSION=$(echo $TAG_DATA | jq .tags | jq '.[0].name' -r)
          if [ "$TAG_VERSION" = "null" ]; then
            TAG_VERSION="v0.0.0"
            FIRST_CATALOG_RUN=true
          else
            FIRST_CATALOG_RUN=false
          fi
          echo "OLD_CATALOG_VERSION=$(echo $TAG_VERSION)" >> $GITHUB_ENV
          echo "FIRST_CATALOG_RUN=$(echo $FIRST_CATALOG_RUN)" >> $GITHUB_ENV
        shell: bash
        env:
          TOKEN: ${{ secrets.QUAY_API_TOKEN }}

      - name: Confirm variables
        run: |
          echo "::notice::INCREMENT_DEVOPS_VERSION = $INCREMENT_DEVOPS_VERSION"
          echo "::notice::INCREMENT_CATALOG_VERSION = $INCREMENT_CATALOG_VERSION"
          echo "::notice::BRANCH = $BRANCH"
          echo "::notice::FIRST_CATALOG_RUN = $FIRST_CATALOG_RUN"
          echo "::notice::OLD_VERSION = $OLD_VERSION"

          if [ -z "$OLD_VERSION" ]
          then
            echo "::error::Tag for $BRANCH not found.  Run manually."
            exit 1
          fi
        shell: bash

      - name: Install Operator SDK
        run: |
          export ARCH=$(case $(uname -m) in x86_64) echo -n amd64 ;; aarch64) echo -n arm64 ;; *) echo -n $(uname -m) ;; esac)
          export OS=$(uname | awk '{print tolower($0)}')

          export OPERATOR_SDK_DL_URL=https://github.com/operator-framework/operator-sdk/releases/download/v1.15.0
          curl -LO ${OPERATOR_SDK_DL_URL}/operator-sdk_${OS}_${ARCH}

          gpg --keyserver keyserver.ubuntu.com --recv-keys 052996E2A20B5C7E

          curl -LO ${OPERATOR_SDK_DL_URL}/checksums.txt
          curl -LO ${OPERATOR_SDK_DL_URL}/checksums.txt.asc
          gpg -u "Operator SDK (release) <cncf-operator-sdk@cncf.io>" --verify checksums.txt.asc

          grep operator-sdk_${OS}_${ARCH} checksums.txt | sha256sum -c -

          chmod +x operator-sdk_${OS}_${ARCH} && sudo mv operator-sdk_${OS}_${ARCH} /usr/local/bin/operator-sdk

          rm checksums.txt
          rm checksums.txt.asc
        shell: bash

      - name: Install Openshift CLI Tools
        run: |
          echo $PATH
          curl https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz > openshift-client-linux.tar.gz
          curl https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/latest/opm-linux.tar.gz > opm-linux.tar.gz
          mkdir openshift
          tar -zxvf openshift-client-linux.tar.gz -C openshift
          tar -zxvf opm-linux.tar.gz -C openshift
          echo 'export PATH=$PATH:~/openshift' >> ~/.bashrc && source ~/.bashrc
          sudo mv ./openshift/opm /usr/local/bin/
          rm openshift-client-linux.tar.gz
          rm opm-linux.tar.gz
        shell: bash

      - name: Log current versions
        run: |
          echo "::notice::yq version"
          yq --version
          echo "::notice::docker version"
          docker --version
          echo "::notice::operator-sdk version"
          operator-sdk version
          echo "::notice::git version"
          git --version
          echo "::notice::opm version"
          opm version
          echo "::notice::helm version"
          helm version
        shell: bash

      - name: Helm Check
        run: |
          helm template devopsinabox-helm-chart --dry-run > /dev/null
          if [ $? -eq 0 ]
          then
            echo "::notice::Helm template devopsinabox-helm-chart compiled successfully."
          else
            echo "::error::Helm template devopsinabox-helm-chart failed to compile."
            exit 1
          fi

          helm template devopsinabox-namespace-helm-chart --dry-run > /dev/null
          if [ $? -eq 0 ]
          then
            echo "::notice::Helm template devopsinabox-namespace-helm-chart compiled successfully."
          else
            echo "::error::Helm template devopsinabox-namespace-helm-chart failed to compile."
            exit 1
          fi

          helm template spring-boot-app-helm-chart --dry-run > /dev/null
          if [ $? -eq 0 ]
          then
            echo "::notice::Helm template spring-boot-app-helm-chart compiled successfully."
          else
            echo "::error::Helm template spring-boot-app-helm-chart failed to compile."
            exit 1
          fi

          helm template dotnet-app-helm-chart --dry-run > /dev/null
          if [ $? -eq 0 ]
          then
            echo "::notice::Helm template dotnet-app-helm-chart compiled successfully."
          else
            echo "::error::Helm template dotnet-app-helm-chart failed to compile."
            exit 1
          fi
        shell: bash

      # Login
      - name: Login to Quay Registry
        run: |
          docker login -u $QUAY_USERNAME -p $QUAY_PASSWORD quay.io
        shell: bash
        env:
          QUAY_USERNAME: ${{ secrets.QUAY_ROBOT_USERNAME }}
          QUAY_PASSWORD: ${{ secrets.QUAY_ROBOT_PASSWORD }}

      - name: Generate operator files
        run: |
          mkdir devopsinabox
          cd devopsinabox
    
          operator-sdk init --plugins=helm --domain=com.perficient --group=apimc --version=v1alpha1 --kind=DevSecOpsManager --helm-chart=../devopsinabox-helm-chart
          operator-sdk create api --group=apimc --version=v1alpha1 --kind=ManagedNamespace --helm-chart=../devopsinabox-namespace-helm-chart
          operator-sdk create api --group=apimc --version=v1alpha1 --kind=SpringBootApp --helm-chart=../spring-boot-app-helm-chart
          operator-sdk create api --group=apimc --version=v1alpha1 --kind=DotNetApp --helm-chart=../dotnet-app-helm-chart

          rm -Rf ../devopsinabox-operator/helm-charts

          cp -R . ../devopsinabox-operator
          cd ../devopsinabox-operator
          
          cat << EOF >> config/default/kustomization.yaml
          patches:
          - path: manager-memory.yaml
          EOF

          cat <<EOF >> config/rbac/role.yaml
          - verbs:
            - "*"
            apiGroups:
            - "batch"
            resources:
            - "jobs"
          EOF

          export VERSION=$(../tools/increment_version.sh $OLD_VERSION $INCREMENT_DEVOPS_VERSION)-$BRANCH
          export IMG=quay.io/$ORGANIZATION/devopsinabox-operator:v$VERSION
          export BUNDLE_IMG=quay.io/$ORGANIZATION/devopsinabox-operator-bundle:v$VERSION

          echo "old version: $OLD_VERSION"
          echo "version: $VERSION"
          echo "img: $IMG"
          echo "bundle img: $BUNDLE_IMG"

          yq -i eval '.spec.version = "'$VERSION'"' config/manifests/bases/devopsinabox.clusterserviceversion.yaml
          yq -i eval '.metadata.annotations.containerImage = "'$IMG'"' config/manifests/bases/devopsinabox.clusterserviceversion.yaml
          DATE="$(date +'%Y-%m-%d %H:%M:%SZ')"
          yq -i eval '.metadata.annotations.createdAt = "'"$DATE"'"' config/manifests/bases/devopsinabox.clusterserviceversion.yaml
          if [[ $FIRST_RUN == false ]]
          then
            REPLACES=devopsinabox.$OLD_VERSION
            echo "REPLACES: $REPLACES"
            yq -i eval '.spec.replaces = "'$REPLACES'"' config/manifests/bases/devopsinabox.clusterserviceversion.yaml
          else
            yq -i 'del(.spec.replaces)' config/manifests/bases/devopsinabox.clusterserviceversion.yaml
          fi
          NAME=devopsinabox.v$VERSION
          echo "NAME: $NAME"
          yq -i eval '.metadata.name = "'$NAME'"' config/manifests/bases/devopsinabox.clusterserviceversion.yaml

          make bundle CHANNELS=$BRANCH DEFAULT_CHANNEL=$BRANCH
          make docker-build docker-push
          make bundle-build
          docker push $BUNDLE_IMG

          export CATALOG_VERSION=$(../tools/increment_version.sh $OLD_CATALOG_VERSION $INCREMENT_CATALOG_VERSION)
          export CATALOG_IMAGE_LATEST=quay.io/$ORGANIZATION/operators-catalog:latest
          export CATALOG_IMAGE_VERSION=quay.io/$ORGANIZATION/operators-catalog:v$CATALOG_VERSION
          if [[ $FIRST_CATALOG_RUN == false ]]
          then
            opm index add --bundles $BUNDLE_IMG --from-index $CATALOG_IMAGE_LATEST --tag $CATALOG_IMAGE_VERSION --build-tool docker --pull-tool docker --debug
          else
            opm index add --bundles $BUNDLE_IMG --tag $CATALOG_IMAGE_VERSION --build-tool docker --pull-tool docker --debug
          fi
          docker tag $CATALOG_IMAGE_VERSION $CATALOG_IMAGE_LATEST
          docker push $CATALOG_IMAGE_LATEST
          docker push $CATALOG_IMAGE_VERSION
        shell: bash