name: DevOpsInABox Production

on:
  workflow_dispatch:

jobs:
  build_devopsinabox:

    name: Deploy DevOpsInABox to Production
    runs-on: ubuntu-latest
    timeout-minutes: 4
    steps:

      - name: Check Quay connection
        run: |
          STATUS=$(curl --location --request GET 'https://quay.io/api/v1/repository/'"$ORGANIZATION"'/operators-catalog/tag?limit=1' --header 'Authorization: Bearer $TOKEN' -s -o /dev/null -w '%{http_code}')
          if [ "$STATUS" -ge "400" ]; then
            echo "::error::Cannot connect to Quay API.  Status code is $STATUS"
            exit 1
          fi
        shell: bash
        env:
          TOKEN: ${{ secrets.QUAY_API_TOKEN }}
          ORGANIZATION: ${{ secrets.QUAY_ORGANIZATION }}

      - name: Get version to deploy
        run: |
          TAG_DATA=$(curl --location --request GET 'https://quay.io/api/v1/repository/'"$ORGANIZATION"'/operators-catalog/tag?limit=1&onlyActiveTags=true' --header 'Authorization: Bearer $TOKEN')
          TAG_ARRAY=$(echo $TAG_DATA | jq .tags)

          if [ "$TAG_ARRAY" = "[]" ]; then
            echo "FIRST_RUN=true" >> $GITHUB_ENV
            TAG_VERSION="v0.0.1"
            echo "DEPLOY_VERSION=$(echo $TAG_VERSION)" >> $GITHUB_ENV
          else
            echo "FIRST_RUN=false" >> $GITHUB_ENV
            TAG_VERSION=$(echo "$TAG_ARRAY" | jq -r '.[0].name' )
            echo "DEPLOY_VERSION=$(echo $TAG_VERSION)" >> $GITHUB_ENV
          fi
        shell: bash
        env:
          TOKEN: ${{ secrets.QUAY_API_TOKEN }}
          ORGANIZATION: ${{ secrets.QUAY_ORGANIZATION }}

      # Login
      - name: Login to Quay Registry
        run: |
          docker login -u $QUAY_USERNAME -p $QUAY_PASSWORD quay.io
        shell: bash
        env:
          QUAY_USERNAME: ${{ secrets.QUAY_ROBOT_USERNAME }}
          QUAY_PASSWORD: ${{ secrets.QUAY_ROBOT_PASSWORD }}

      - name: Push dev catalog to prod
        run: |

          export CATALOG_IMAGE_DEV_LATEST=quay.io/$ORGANIZATION/operators-catalog:latest
          export CATALOG_IMAGE_LATEST=quay.io/$ORGANIZATION/operators-catalog-prod:latest
          export CATALOG_IMAGE_VERSION=quay.io/$ORGANIZATION/operators-catalog-prod:v$DEPLOY_VERSION

          docker pull $CATALOG_IMAGE_DEV_LATEST
          docker tag $CATALOG_IMAGE_VERSION $CATALOG_IMAGE_DEV_LATEST
          docker tag $CATALOG_IMAGE_LATEST $CATALOG_IMAGE_DEV_LATEST
          docker push $CATALOG_IMAGE_VERSION
          docker push $CATALOG_IMAGE_LATEST
        shell: bash
        env:
          ORGANIZATION: ${{ secrets.QUAY_ORGANIZATION }}