name: DevOpsInABox copy

on:
  workflow_dispatch:

jobs:
  build_devopsinabox:

    name: Deploy DevOpsInABox to Production
    runs-on: ubuntu-latest
    timeout-minutes: 4
    steps:

      - name: Check Quay connection
        run: |
          curl --location --request DELETE 'https://quay.io/api/v1/repository/shawn_stout_org/operators-catalog/tag/latest' --header 'Authorization: Bearer 81dMRBlNkusu38MihuyGUSZeuOhmzK0XuK0kGEKu'
        shell: bash
        env:
          TOKEN: ${{ secrets.QUAY_API_TOKEN }}
          ORGANIZATION: ${{ secrets.QUAY_ORGANIZATION }}
