name: DevOpsInABox

on:
  push:
    branches:
    - aws
    - azure
  workflow_dispatch:
    inputs:
      increment_devops_version:
        type: choice
        description: Version increment for devopsinabox
        required: true
        default: 'patch'
        options:
        - major
        - minor
        - patch
      increment_catalog_version:
        type: choice
        description: Version increment for catalog
        required: true
        default: 'patch'
        options:
        - major
        - minor
        - patch
      first_run:
        type: choice
        description: Set to true only if first run
        required: true
        default: 'false'
        options:
        - true
        - false

jobs:
  build_devopsinabox:

    name: Build and Deploy DevOpsInABox
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:

      - name: Extract branch name
        shell: bash
        run: |
          if ! [ ${GITHUB_REF#refs/heads/} == "aws" ] || [ ${GITHUB_REF#refs/heads/} == "azure" ]; then
            echo "::error::Branch must be 'aws' or 'azure'"
            exit 1
          fi
          echo "FIRST_RUN=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
        id: extract_branch

      - name: Log inputs deva
        run: |
          echo "::notice::increment_devops_version = ${{ inputs.increment_devops_version }}"
          echo "::notice::increment_catalog_version = ${{ inputs.increment_catalog_version }}"
          echo "::notice::first_run = $FIRST_RUN"
        shell: bash

